[package]
name = "ports"
version = "0.9.0"
edition = "2024"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "List listening ports."
license = "MIT OR Apache-2.0"
repository = "https://github.com/qrichert/ports.git"
readme = "README.md"
keywords = ["ports", "listening-ports", "tcp", "process", "network"]
categories = ["command-line-utilities", "network-programming"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
# Output text through a pager.
lessify = "0.6.0"
# Output in tabular format.
verynicetable = "0.6.3"
